query allPalettes ($first: Int, $skip: Int, $orderBy: PaletteOrderBy) {
  allPalettes(first: $first, skip: $skip, orderBy: $orderBy) {
    id
    title
    colors
    stats {
      id
      clicks
    }
    votes {
      id
      user {
        id
      }
    }
  }
  totalCount: _allPalettesMeta {
    count
  }
}
